.gitignore
README.md
uxsim/utils.py
uxsim/uxsim.py

Change the definition of actual travel time from departure time-based to arrival time-based, which is more appropriate. 
Add Route class for convenience.

Correct actual travel time, Add Route class

---

README.md

Add PyPI badge to show most recent version available on PyPI. This helps users to quickly find the latest released version.
[![PyPi](https://img.shields.io/pypi/v/uxsim.svg)](https://pypi.python.org/pypi/uxsim)

README.md: Add PyPI badge to show most recent version

---

.gitignore

This stop PyCharm files from being tracked in git.

gitignore: Add .idea/

---

.pre-commit-config.yaml
README.md
demos_and_examples/example_01_basic.py
demos_and_examples/example_01en_basic.py
demos_and_examples/example_02_bottleneck.py
demos_and_examples/example_03_read_from_csv_sioux_falls_network.py
demos_and_examples/example_04_automatic_network_generation.py
demos_and_examples/example_05_gridlock_and_prevention.py
demos_and_examples/example_06_dynamic_parameter_change.py
demos_and_examples/example_07_signal.py
demos_and_examples/example_08_signal_reactive_control.py
demos_and_examples/example_08en_signal_reactive_control.py
demos_and_examples/example_09en_congestion_pricing_highway_toll.py
demos_and_examples/example_11en_signal_4legged_intersection_reactive_control.py
demos_and_examples/example_12en_signal_4legged_intersection_Deep_Reinforcement_Learning_pytorch_control.py
demos_and_examples/example_14en_multiple_signals_Deep_Reinforcement_Learning_pytorch.py
demos_and_examples/uxsim/utils.py
demos_and_examples/uxsim/utils/Licence_of_Inconsolata.otf.txt
demos_and_examples/uxsim/uxsim.py
setup.py
uxsim/utils.py
uxsim/utils/Licence_of_Inconsolata.otf.txt
uxsim/uxsim.py

This commit adds a [pre-commit](https://pre-commit.com/) configuration, which allows running a few tools automatically both locally and in CI.
Currently:
- It adds [pyupgrade](https://github.com/asottile/pyupgrade)
- It check for trailing whitespaces and if toml and yaml syntax is correct
- Updates itself monthly (using [pre-commit.ci](https://pre-commit.ci/))
For automatically running pre-commit in CI, I would recommend enabling it on https://pre-commit.ci/.

Add pre-commit configuration, upgrade to Python 3.9+ syntax, remove trailing whitespaces

---

.github/workflows/run-examples.yml
demos_and_examples/test_examples.py

This pull request integrates pytest within our GitHub Actions CI pipeline to automatically execute all example scripts located in the `demos_and_examples` directory. This ensures that every commit or pull request can be verified that all existing examples keep working when changes are made.
- Added `test_examples.py`: A pytest wrapper script that dynamically discovers and runs each `.py` file in `demos_and_examples` as a separate test case.
- Updated `.github/workflows/python-app.yml`: Configured the CI pipeline to set up pytest and run the wrapper script as part of the testing jobs.
- Added `pytest` to the project dependencies to enable automated test discovery and execution.
The `test_examples.py` script utilizes pytest's `pytest_generate_tests` hook to collect all the Python scripts in …

Test examples in CI

---

README.md
demos_and_examples/example_00en_simple.py
demos_and_examples/example_01en_basic.py
demos_and_examples/example_01jp_basic.py
demos_and_examples/example_02en_bottleneck.py
demos_and_examples/example_02jp_bottleneck.py
demos_and_examples/example_03en_read_from_csv_sioux_falls_network.py
demos_and_examples/example_03jp_read_from_csv_sioux_falls_network.py
demos_and_examples/example_04en_automatic_network_generation.py
demos_and_examples/example_04jp_automatic_network_generation.py
demos_and_examples/example_05en_gridlock_and_prevention.py
demos_and_examples/example_05jp_gridlock_and_prevention.py
demos_and_examples/example_06en_dynamic_parameter_change.py
demos_and_examples/example_06jp_dynamic_parameter_change.py
demos_and_examples/example_07en_signal.py
demos_and_examples/example_07jp_signal.py
demos_and_examples/example_08en_signal_reactive_control.py
demos_and_examples/example_08jp_signal_reactive_control.py
demos_and_examples/example_09en_congestion_pricing_highway_toll.py
demos_and_examples/example_10en_signal_4legged_intersection.py
uxsim/uxsim.py

UXsim is now available at conda-forge. Thanks maintainers!

Update docs (including conda instruction) and examples

---

tests/test_other_functions.py
uxsim/analyzer.py
uxsim/uxsim.py

This addresses https://github.com/toruseo/UXsim/issues/78

Add GPS-like log

---

tests/test_verification_exceptional.py
uxsim/uxsim.py

This addresses https://github.com/toruseo/UXsim/issues/99

Add hard deterministic mode

---

tests/test_other_functions.py
uxsim/analyzer.py
uxsim/uxsim.py

this addresses https://github.com/toruseo/UXsim/issues/102

Add area and vehicle group settings and analysis

---

.github/codecov.yml
tests/test_other_functions.py
uxsim/analyzer.py

this is also related to https://github.com/toruseo/UXsim/issues/102

add area stats

---

tests/test_other_functions.py
uxsim/uxsim.py

solves 1st and 2nd tasks in https://github.com/toruseo/UXsim/issues/133

update shortest path cost funcs and add test

---

tests/test_other_functions.py
uxsim/Utilities/Utilities.py
uxsim/uxsim.py

related to https://github.com/toruseo/UXsim/issues/133

relocate 'get_shortest_path_*()' to `Utilities` submodule

---

tests/test_other_functions.py
uxsim/Utilities/Utilities.py
uxsim/uxsim.py

complete https://github.com/toruseo/UXsim/issues/133

add shortest path cost on t

---

tests/test_other_functions.py
uxsim/__init__.py
uxsim/scenario_reader_writer.py
uxsim/uxsim.py

This addresses https://github.com/toruseo/UXsim/issues/140

add `adddemand_nodes2nodes2` and `adddemand_area2area2`

---

demos_and_examples/example_16en_import_from_OpenStreetMap.py
tests/test_examples.py
tests/test_other_functions.py
uxsim/OSMImporter/OSMImporter.py

This addresses https://github.com/toruseo/UXsim/issues/147

Fix OSMnx version issue

---

paper/paper.md

Some minor language-related edits relating to the review for submission to JOSS.
See https://github.com/openjournals/joss-reviews/issues/7617

Minor language changes

---

README.md
tests/README.md
tests/test_other_functions.py

This addresses JOSS review comments https://github.com/openjournals/joss-reviews/issues/7617

update tests and docs

---

paper/paper.md

See https://github.com/openjournals/joss-reviews/issues/7617

Fixed two typos in the manuscript

---

demos_and_examples/example_26en_dynamic_traffic_assignment_DUO_DUE_DSO.py

Due to this random error: https://github.com/toruseo/UXsim/issues/159#issuecomment-2612271923

temporally disabled example26

---

tests/test_other_functions.py
tests/test_verification_straight_road.py
uxsim/utils.py
uxsim/uxsim.py

This fixes https://github.com/toruseo/UXsim/issues/176

Fix vehicle speed error at node

---

uxsim/analyzer.py

This addresses https://github.com/toruseo/UXsim/issues/172

add legends for `network`, `network_average`, `network_anim`

---

.gitignore
tests/test_other_functions.py
uxsim/analyzer.py

This finally addresses https://github.com/toruseo/UXsim/issues/65

Add "flow_speed" visualization mode for network plot

---

uxsim/DTAsolvers/DTAsolvers.py

This addresses https://github.com/toruseo/UXsim/issues/213

add warning for DUE solver
